Spawn:
  World: world
  X: 0.5
  Y: 1
  Z: 0.5
  yaw: 180
  pitch: 0
Door:
  World: world
  1:
    X: 20.0
    Y: 1.0
    Z: -2.0
  2:
    X: 20.0
    Y: 3.0
    Z: 2.0
Join-Message:
  Actionbar: "Welcome back %PLAYER%"
Database:
  host: "jdbc:mysql://localhost:3306/mysql"
  username: "root"
  password: "test or whatever other password"