name: lobby
version: '${project.version}'
main: com.x_tornado10.lobby.Lobby
api-version: '1.20'
authors: [x_Tornado10]
description: Lobby plugin
commands:
  lobby:
    aliases:
      - l
      - hub
    description: teleports you to the lobby
    permission: lobby.player
  setrank:
    aliases:
      - rank
      - setr
    description: Grants a rank to players
    permission: lobby.admin
  setsuffix:
    aliases:
      - suffix
      - setsuffx
    description: Set your own Suffix
    permission: lobby.player
depend:
  - LuckPerms
permissions:
  lobby.builder:
    description: builder
  lobby.cs+:
    description: CS+ rank
  lobby.csp:
    description: CSP rank